### ISSUE TITLE
Replace in markdown frontmatter

### ISSUE THREAD

**Issue by cedricdelpoux** [gaurav-nelson/gatsby-remark-replace#1]
Hi, 

I would need to replace some text in frontmatter as well. 
I have a client using a CMS committing markdown files to a repository with wrong urls.

```
---
image: /wrong-folder/my-file/jpg
---
My content has ![](/wrong-folder/my-file/jpg) images with wrong paths too
```

What about adding this feature?
Thank you

**Comment by gaurav-nelson** [comment]
Thanks @cedricdelpoux I request you to please create an issue in the original library at https://github.com/angeloashmore/gatsby-remark-find-replace and use that in your projects. I've created this module only because I wanted to replaces things and [my PR](https://github.com/angeloashmore/gatsby-remark-find-replace/pull/2) was pending merge.

**Comment by cedricdelpoux** [comment]
I understand. 

Now you deprecated this package and don't want to maintain it anymore. 
Could you accept to transfer me the `npm` package `gatsby-plugin-replace`? 

I would like do do my own.

Thank you very much 🙏🏻

**Comment by gaurav-nelson** [comment]
Thanks @cedricdelpoux sure I can.
